### ISSUE TITLE
Admin Setting to Disable Day/Night Cycle Lock

### ISSUE THREAD

**Issue by northwesttreesgaming** [northwesttrees-gaming/Real-Time-Mod#13]
# Feature
Make it possible to disable the day/night locking system so some mods can use the calendar without a day/night locking system.

## Features
- [ ] Make a map setting to enable/disable day/night locking.
- [ ] Adapt code to work with the new system for setting the world time.

## Related
- #6

**Comment by northwesttreesgaming** [comment]
Time can be disabled/enabled using the following command in 1.6.0 and up.
``/realtimemod admin realTime false|true``

**Comment by xFirefalconx** [comment]
Hi, question regarding this. There is no general config to do this, but a gamerule for each world, right? I would like to set it to default false in each world for my modpack, that's why I was asking for the feature. I cannot save the gamerules globally on 1.18.2. I don't know if that involves a lot of extra work but I hope this is possible to set up 🙏
